name = "UnfoldBIDS"
uuid = "b54e767b-1ebd-4480-ac2a-f5f4d8853074"
authors = ["Rene Skukies", "Benedikt Ehinger", "Jan Haas"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
PyMNE = "6c5003b2-cbe8-491c-a0d1-70088e6a0fd6"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"

[compat]
MixedModels = "4"
StatsModels = "0.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
