name = "UnfoldBIDS"
uuid = "b54e767b-1ebd-4480-ac2a-f5f4d8853074"
authors = ["Rene Skukies", "Benedikt Ehinger", "Jan Haas"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
CSVFiles = "5d742f6a-9f54-50ce-8119-2520741973ca"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
MixedModels = "ff71e718-51f3-5ec2-a782-8ffcbfa3c316"
PyMNE = "6c5003b2-cbe8-491c-a0d1-70088e6a0fd6"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unfold = "181c99d8-e21b-4ff3-b70b-c233eddec679"

[compat]
AlgebraOfGraphics = "0.6"
CSVFiles = "1"
CairoMakie = "0.7"
DataFrames = "1"
MixedModels = "4"
PyMNE = "0.1"
Revise = "3"
StatsModels = "0.6"
Unfold = "0.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
